# -*- coding: utf-8 -*-
"""multi variate.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Wc4a5Dzs06gxaDeyJqAkAxB5of9bblJs
"""

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn import linear_model
from sklearn.model_selection import train_test_split

data=pd.read_csv('/content/Company_data.csv')

data.head()

data.info()

data.describe()

data.shape

data.isnull()

dt=data.corr()

sns.heatmap(dt,annot=True)

x= data.drop('Sales', axis=1).values
y = data['Sales'].values
x_t,x_tt,y_t,y_tt=train_test_split(x,y,test_size=0.30,random_state=0)

print(x_t.shape)

print(y_t.shape)

y_t=y_t.reshape(-1,1)

reg=linear_model.LinearRegression()
reg.fit(x_t,y_t)

print(x_tt.shape)

y_pre=reg.predict(x_tt)

print(y_tt.shape)

#Evaluating the model on training data only
from sklearn.metrics import mean_absolute_error,r2_score,mean_squared_error
y_pre= reg.predict(x_tt)

print(f'MAE = {mean_absolute_error(y_tt, y_pre)}')
print(f'MSE = {mean_squared_error(y_tt, y_pre)}')
print(f'RMSE = {np.sqrt(mean_squared_error(y_tt, y_pre))}')
print(f'R_2 = {r2_score(y_tt, y_pre)}')

